<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Testing" />
    <PackageReference Include="Dapper" />
    <ProjectReference Include="../../src/SwiftBets.Payout.Infrastructure/SwiftBets.Payout.Infrastructure.csproj" />
    <ProjectReference Include="../../src/SwiftBets.Payout.Migrator/SwiftBets.Payout.Migrator.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>
</Project>
